global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093" # alert instance ip

rule_files:
  - alertrules.yml   # alert rule file

scrape_configs:
- job_name: 'node-exporter'
  file_sd_configs:
  - files:
    - 'targets.json'

- job_name: 'prometheus'
  file_sd_configs:
  - files:
    - 'targets.json'

- job_name: 'alertmanager'
  file_sd_configs:
  - files:
    - 'targets.json'
